name: comedian_images_selector
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: "^5.0.0-alpha+4"
  angular_components: "^0.9.0-alpha+3"
  firebase: "^4.3.0"
  sass_builder: '^1.0.0'
  comiko_shared:
    git: https://github.com/comiko-app/shared
  meta: '^1.1.2'
  angular_router: "^2.0.0-alpha+4"

dev_dependencies:
  build_runner: '^0.7.8'
  build_web_compilers: ^0.2.1
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
dependency_overrides:
    analyzer: ^0.31.0-alpha.1

transformers:
- sass_builder
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
